FROM ubuntu
ARG DEBIAN_FRONTEND=noninteractive

WORKDIR /tmp

RUN apt-get update && apt-get install -y \
    python3.7 \
    python3-pip \
    python3-opencv \
    python3-numpy \
    mosquitto \
    mosquitto-clients

RUN pip3 install paho-mqtt
